[tool.black]
line-length = 127
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 127
known_first_party = ["activity_tracker", "config", "database", "main", "notifications", "render_api", "status_monitor"]
